#ifndef CACP_COMMANDS_PRIV_H_INCLUDED
#define CACP_COMMANDS_PRIV_H_INCLUDED

#include "config.h"

enum command_type {
	CACP_COMMAND_LOGIN,
	CACP_COMMAND_LOGINFORCE,
	CACP_COMMAND_RESUME,
	CACP_COMMAND_LOGOUT,
	CACP_COMMAND_NOOP,

	CACP_COMMAND_REVERT,
	CACP_COMMAND_COMMIT,
	CACP_COMMAND_CURRENT,
	CACP_COMMAND_UPDATE,
	CACP_COMMAND_DIRTY,

	CACP_COMMAND_LIST,
	CACP_COMMAND_LISTR,
	CACP_COMMAND_MLIST,
	CACP_COMMAND_MLISTR,
	CACP_COMMAND_ATTR,
	CACP_COMMAND_MATTR,
	CACP_COMMAND_ACCESS,
	CACP_COMMAND_MACCESS,

	CACP_COMMAND_GET,
	CACP_COMMAND_SET,
	CACP_COMMAND_ADD,
	CACP_COMMAND_DEL,
	CACP_COMMAND_MOVE,

	CACP_COMMAND_SUBMIT,

	CACP_COMMAND_ADMIN,
	CACP_COMMAND_INFO,

	CACP_COMMAND_FUNCLIST,
	CACP_COMMAND_EVAL,
};

enum subcommand_type {
	CACP_SUBCOMMAND_ADD,
	CACP_SUBCOMMAND_DEL,
	CACP_SUBCOMMAND_SET,
	CACP_SUBCOMMAND_MOVE
};

#endif /* CACP_COMMANDS_PRIV_H_INCLUDED */
